choco install nodejs.install -y
choco install dotnetcore -y
choco install dotnetcore-runtime.install -y	
choco install mssqlserver2014express -y
choco install mssqlservermanagementstudio2014express -y
choco install googlechrome -y
choco install 7zip -y
choco install sql-server-management-studio -y
choco install visualstudio2017enterprise -y
choco install visualstudiocode -y
choco install conemu -y
choco install notepadplusplus.install -y
choco install git-credential-manager-for-windows -y
choco install windowsazurepowershell -y
choco install git.install -y
choco install clipx -y
choco install dropbox -y
choco install office365homepremium -y
choco install skype -y
choco install ccleaner -y
choco install curl -y
choco install sublimetext2 -y
choco install whatsapp -y
